/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fdf8f8",
        "surface-dim": "#ddd9d8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3f2",
        "surface-container": "#f1edec",
        "surface-container-high": "#ebe7e6",
        "surface-container-highest": "#e5e2e1",
        "surface-dark": "#101010",
        "surface-dark-elevated": "#1a1a1a",
        "surface-soft": "#f8f9fa",
        "surface-card": "#f5f5f5",
        "surface-strong": "#e5e7eb",
        canvas: "#ffffff",
        hairline: "#e5e7eb",
        "hairline-soft": "#f3f4f6",
        ink: "#111111",
        body: "#374151",
        muted: "#6b7280",
        "muted-soft": "#898989",
        primary: "#000000",
        "primary-active": "#242424",
        secondary: "#0058be",
        "on-dark": "#ffffff",
        "on-dark-soft": "#a1a1aa",
        "badge-orange": "#fb923c",
        "badge-pink": "#ec4899",
        "badge-violet": "#8b5cf6",
        "badge-emerald": "#34d399",
        success: "#10b981",
        warning: "#f59e0b",
        error: "#ef4444",
        "error-container": "#ffdad6",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
      },
      borderRadius: {
        DEFAULT: "6px",
        md: "8px",
        lg: "10px",
        xl: "12px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "20px",
        xl: "24px",
        xxl: "32px",
        section: "64px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Manrope", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        code: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-md": ["28px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "700" }],
        "display-sm": ["22px", { lineHeight: "1.25", letterSpacing: "0", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "1.35", letterSpacing: "0", fontWeight: "600" }],
        "title-md": ["15px", { lineHeight: "1.45", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.45", letterSpacing: "0", fontWeight: "400" }],
        button: ["13px", { lineHeight: "1", letterSpacing: "0", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
      },
      boxShadow: {
        panel: "0 16px 42px rgba(17, 17, 17, 0.08)",
        subtle: "0 1px 2px rgba(0, 0, 0, 0.05)",
      },
    },
  },
  plugins: [],
};
