/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f4f7fb",
        "surface-dim": "#d8e0ea",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf2f8",
        "surface-container": "#e7edf5",
        "surface-container-high": "#dfe7f1",
        "surface-container-highest": "#d5dfeb",
        "surface-dark": "#0b1018",
        "surface-dark-elevated": "#151c27",
        "surface-tint": "#263242",
        "surface-variant": "#e7eef8",
        "surface-soft": "#eef3f9",
        "surface-card": "#ffffff",
        "surface-strong": "#dbe5f0",
        canvas: "#fbfcff",
        hairline: "#dbe4ee",
        "hairline-soft": "#edf2f7",
        ink: "#101828",
        body: "#344054",
        muted: "#667085",
        "muted-soft": "#98a2b3",
        primary: "#2f7ee6",
        "primary-active": "#1f6fd8",
        secondary: "#0f766e",
        "on-dark": "#eaf0f8",
        "on-dark-soft": "#9aa9ba",
        "badge-orange": "#fb923c",
        "badge-pink": "#ec4899",
        "badge-violet": "#8b5cf6",
        "badge-emerald": "#34d399",
        success: "#10b981",
        warning: "#f59e0b",
        error: "#ef4444",
        "error-container": "#ffdad6",
        outline: "#747878",
        "outline-variant": "#c4c7c7",
      },
      borderRadius: {
        DEFAULT: "6px",
        md: "8px",
        lg: "10px",
        xl: "12px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "20px",
        xl: "24px",
        xxl: "32px",
        section: "64px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Manrope", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        code: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-md": ["28px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "700" }],
        "display-sm": ["22px", { lineHeight: "1.25", letterSpacing: "0", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "1.35", letterSpacing: "0", fontWeight: "600" }],
        "title-md": ["15px", { lineHeight: "1.45", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.45", letterSpacing: "0", fontWeight: "400" }],
        button: ["13px", { lineHeight: "1", letterSpacing: "0", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "500" }],
      },
      boxShadow: {
        panel: "0 18px 54px rgba(16, 24, 40, 0.12)",
        subtle: "0 1px 2px rgba(16, 24, 40, 0.08)",
      },
    },
  },
  plugins: [],
};
